# Generated by Django 5.2.17 on 2026-09-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=64, unique=True)),
                ("shopify_customer_id", models.CharField(max_length=32, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "line_user_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("rx_snapshot", models.JSONField(blank=True, default=dict)),
                ("last_sync_error", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=32, unique=True)),
                ("supplier", models.CharField(db_index=True, max_length=128)),
                ("method", models.CharField(default="fax_pdf", max_length=16)),
                ("file_path", models.CharField(blank=True, max_length=512)),
                ("dispense_record_ids", models.JSONField(default=list)),
                ("order_names", models.JSONField(default=list)),
                ("line_count", models.PositiveIntegerField(default=0)),
                ("box_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_error", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_id", models.CharField(max_length=128, unique=True)),
                ("topic", models.CharField(db_index=True, max_length=64)),
                ("shop_domain", models.CharField(blank=True, max_length=128)),
                ("resource_id", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("processing", "processing"),
                            ("done", "done"),
                            ("pending_retry", "pending_retry"),
                            ("failed", "failed"),
                            ("skipped", "skipped"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("staff_alerted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrderVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=64, unique=True)),
                ("order_name", models.CharField(blank=True, max_length=32)),
                ("shopify_customer_id", models.CharField(blank=True, max_length=32)),
                (
                    "patient_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("rejected", "rejected"),
                            ("pending", "pending"),
                            ("cancelled", "cancelled"),
                            ("error", "error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("lines", models.JSONField(blank=True, default=list)),
                ("delivery", models.CharField(blank=True, max_length=16)),
                ("shipping_address", models.JSONField(blank=True, default=dict)),
                ("dispense_record_ids", models.JSONField(blank=True, default=list)),
                ("action", models.CharField(blank=True, max_length=64)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bridge.webhookevent",
                    ),
                ),
            ],
        ),
    ]
